### ISSUE TITLE
Anzeigefehler Verspätungen

### ISSUE THREAD

**Issue by DerHero** [Gegreenpeaced/LOTUS-Leitstellentool#25]
![image](https://user-images.githubusercontent.com/42517031/87254332-360f8200-c482-11ea-9b36-c94915f4e5c4.png)

"pünktlich min"

das min sollte in diesem Fall weg.

**Comment by Gegreenpeaced** [comment]
Einfach mal die Browser Daten löschen. Eig. ist dieser Bug behoben
