### ISSUE TITLE
E-Mailansicht im Handy

### ISSUE THREAD

**Issue by MineTim** [Gegreenpeaced/LOTUS-Leitstellentool#28]
![Screenshot_20200712-142438_Email](https://user-images.githubusercontent.com/26803527/87826151-a6e6dd80-c878-11ea-8d4b-57f0d3044d40.jpg)

So aufgenommen in "E-Mail" von Galaxy auf dem Handy (standardmäßig installiert)

**Comment by Gegreenpeaced** [comment]
Nunja, es gibt zwei Möglichkeiten zur Lösung:

1. Mails ohne Design verschicken
2. Responsive Design (kein Bock)
3. Nutzer müssten Mail Programm wechseln.

**Comment by MineTim** [comment]
Das ist blöd :/

Ich für meinen Part weiß ja was drin steht - aber es gibt sicherlich Leute, die das nicht wissen :/

**Comment by Gegreenpeaced** [comment]
hmm, ich mache ne Abstimmung auf Discord :)

**Comment by Gegreenpeaced** [comment]
DONE! Mail Service wurde auf Variante 1 geändert!
