### ISSUE TITLE
Anmeldung deaktivieren - Feedback

### ISSUE THREAD

**Issue by MineTim** [Gegreenpeaced/LOTUS-Leitstellentool#30]
Sofern die Anmeldung deaktiviert wird, kommt eine Meldung, dass die Anmeldungen gelöscht wurden. Die Formulierung ist dabei irreführend/ungünstig gewählt, kann man diesbezüglich bitte die Formulierung ändern?

Danke schon mal vorab :)

**Comment by Gegreenpeaced** [comment]
DONE!
